### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by thegrumpyenby**
updated Livestream section with correct names and new times — figured it might be a good opportunity for me to practice doing a PR rather than just committing. :) let me know if I done goofed up somehow!

### CODE REVIEW

**Comment by thegrumpyenby** [comment]
@jtfairbank hey, could you please approve this and/or tell me what I did wrong 🙃 I really want to learn!

**Review by jtfairbank — CHANGES_REQUESTED** [review]
**praise:** @thegrumpyenby thanks so much for taking the initiative here!  My apologies for the delay in reviewing, had an off week last week and I tend to try and batch reviews around the tech hangs. :smile: 

**suggestion(blocking):** Could you update this to point at our YouTube livestream link instead of the twitch one?

**suggestion(non-blocking):** I'd recommend adding spaces between the timezone `/` for readability.

**Comment by thegrumpyenby** [comment]
@jtfairbank thanks for the input! I’ve changed things accordingly and pushed the changes to the branch. Does this suffice or do I need to do something else? Do I need to hit “squash and merge”?

**Review by jtfairbank — APPROVED** [review]

**Comment by jtfairbank** [comment]
@thegrumpyenby looks good, got it merged in!  I'm a fan of the "rebase and merge" option as it creates a continuous commit history and prevents merge commits.  It also preserves all the commits you make, which some projects might not like but i think is helpful for projects like ours where folks might want to see the work-in-progress in order to learn how to do something!

**Pull request merged**
